# Generated by Django 4.2 on 2022-12-26 17:06

from django.db import migrations

BRANCH_NAME = "Tennis"
BRANCH_ID = "59b7bd71-1aab-4751-8248-7af4a7790f8c"
COMPLEX_NAME = "Maltepe Sports Complex"
COMPLEX_ID = "6989b491-bb85-414a-b470-293b190ebb44"

GENERIC_INFO = {
    "branch_name": BRANCH_NAME,
    "branch_id": BRANCH_ID,
    "complex_name": COMPLEX_NAME,
    "complex_id": COMPLEX_ID,
}

SPORT_SELECTIONS = [
    {
        "pitch_name": "Closed Court 1",
        "pitch_id": "f64f68a6-7779-4f25-91d2-d7ee7ccda42e",
        **GENERIC_INFO,
    },
    {
        "pitch_name": "Closed Court 2",
        "pitch_id": "b3d358ee-c85b-4773-89b5-2dc14e5bcd5f",
        **GENERIC_INFO,
    },
    {
        "pitch_name": "Closed Court 3",
        "pitch_id": "f21006a3-26d9-480f-aa96-16b45a39e335",
        **GENERIC_INFO,
    },
    {
        "pitch_name": "Closed Court 4",
        "pitch_id": "88c91f40-ef33-42fc-a51f-9cf0e1912079",
        **GENERIC_INFO,
    },
    {
        "pitch_name": "Open Court",
        "pitch_id": "6c93b9bb-1560-4cba-926a-3632d69a05fd",
        **GENERIC_INFO,
    },
]


def add_sport_selections(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SportSelection = apps.get_model("selections", "SportSelection")

    for sport_selection in SPORT_SELECTIONS:
        SportSelection.objects.get_or_create(**sport_selection)


class Migration(migrations.Migration):

    dependencies = [
        ("selections", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_sport_selections)]
